name: Static Code Analysis

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  phpcs:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    runs-on: ubuntu-20.04
    name: Tests code style validation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run PHP_CodeSniffer
        run: docker run --rm -v $(pwd):/data cytopia/phpcs --standard=./phpcs.xml

  stubs:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.4', '8.0' ]

    name: Stubs code validation in PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, json, imagick, gd-php/php-src@PHP-${{ matrix.php }}, gettext, igbinary, apcu, msgpack, memcached, yaml, redis
          ini-values: apc.enable_cli=on, session.save_path=/tmp, extension=psr.so, extension=phalcon.so
          tools: pecl
          env:
            GD_CONFIGURE_OPTS: --enable-gd=shared,/usr --with-external-gd --with-jpeg
            GD_LIBS: libgd-dev libjpeg-dev
            GD_PATH: ext/gd

      - name: Install System Dependencies
        run: |
          sudo apt-get update --quiet --yes 1>/dev/null
          sudo apt-get install --no-install-recommends -q -y re2c

      - name: Install Packages
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: Install Zephir
        run: .ci/install-zephir.sh

      - name: Validate stubs
        if: always()
        run: |
          $HOME/bin/zephir stubs
          vendor/bin/psalm ide/
